# Generated by Django 4.1.3 on 2022-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orders', through='shoesshop.OrderProduct', to='shoesshop.product'),
        ),
    ]
