// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASkeletonAvatar: typeof import('ant-design-vue/es')['SkeletonAvatar']
    ASkeletonButton: typeof import('ant-design-vue/es')['SkeletonButton']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATag: typeof import('ant-design-vue/es')['Tag']
    HomeCarousel: typeof import('./src/components/page/home/HomeCarousel.vue')['default']
    NavButton: typeof import('./src/components/atoms/NavButton.vue')['default']
    Order: typeof import('./src/components/page/order/Order.vue')['default']
    OrderProduct: typeof import('./src/components/page/order/OrderProduct.vue')['default']
    ProductCard: typeof import('./src/components/common/ProductCard/index.vue')['default']
    ProductItem: typeof import('./src/components/page/cart/ProductItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideFilter: typeof import('./src/components/page/products/SideFilter.vue')['default']
    TagCanceled: typeof import('./src/components/atoms/TagCanceled.vue')['default']
    TagDelivered: typeof import('./src/components/atoms/TagDelivered.vue')['default']
    TagProcessing: typeof import('./src/components/atoms/TagProcessing.vue')['default']
    TagShipping: typeof import('./src/components/atoms/TagShipping.vue')['default']
    ViewedProducts: typeof import('./src/components/common/ViewedProducts.vue')['default']
  }
}
