// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ADatePicker: typeof import("ant-design-vue/es")["DatePicker"]
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BuyMoreSuggest: typeof import('./src/components/page/cart/BuyMoreSuggest.vue')['default']
    CartList: typeof import('./src/components/page/cart/CartList.vue')['default']
    ExampleOrganismName: typeof import("./src/components/page_organisms/_example_page_name/ExampleOrganismName.vue")["default"]
    NavButton: typeof import('./src/components/atoms/NavButton.vue')['default']
    Order: typeof import('./src/components/page/order/Order.vue')['default']
    OrderProduct: typeof import('./src/components/page/order/OrderProduct.vue')['default']
    OrganismName: typeof import('./src/components/page/cart/OrganismName.vue')['default']
    ProductCard: typeof import('./src/components/common/ProductCard/index.vue')['default']
    ProductItem: typeof import('./src/components/page/cart/ProductItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuggestBuyMore: typeof import('./src/components/page/cart/SuggestBuyMore.vue')['default']
    TagDelivered: typeof import('./src/components/atoms/TagDelivered.vue')['default']
    TagDelivery: typeof import('./src/components/atoms/TagDelivery.vue')['default']
    TagProcessing: typeof import('./src/components/atoms/TagProcessing.vue')['default']
    TagShipping: typeof import('./src/components/atoms/TagShipping.vue')['default']
  }
}
